version: "3.0"

services:
  mysql_demo:
    container_name: mysql_demo
    image: daocloud.io/library/mysql:8.0.20
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      SQL_DATABASE: chatgpt-application
      SQL_USER: root
      SQL_PASSWORD: xxxxxxx
      SQL_ROOT_HOST: 0.0.0.0
    volumes:
      - ./deploy/mysql/db:/var/lib/mysql #用来存在了数据库表文件
      - ./deploy/mysql/conf/my.cnf:/etc/my.cnf #存放自定义的配置文件
      # 我们在启动 Mysql 容器时自动创建我们需要的数据库和表
      # mysql 官方镜像中提供了容器启动 docker-entrypoint-initdb.d 下的脚本的功能
      - ./deploy/mysql/init:/docker-entrypoint-initdb.d/ #存放初始化的脚本
    networks:
      - my-server_demo

  nest_demo:
    #nestjs 服务
    container_name: server_demo
    build:
      #根据 Dockerfile 构建镜像
      context: .
      dockerfile: Dockerfile
    ports:
      - 3089:3089
    restart: on-failure #设置自动重启，这一步必须设置，主要是存在 mysql 还没有启动完成就启动了 node 服务
    networks:
      - my-server_demo
    depends_on:
      # node 服务依赖于 mysql
      - mysql_demo

networks:
  my-server_demo:
